import { createElement } from "react";
const icon = (name) => (props) => createElement("svg", { ...props, "data-icon": name });
export const Check = icon("check");
export const ChevronDown = icon("chevron-down");
export const ChevronsDownUp = icon("chevrons-down-up");
export const ChevronsUpDown = icon("chevrons-up-down");
export const Search = icon("search");
export const X = icon("x");
export const Globe = icon("globe");
export const Rss = icon("rss");
export const FileText = icon("file-text");
export const Zap = icon("zap");
export const Filter = icon("filter");
